services:
    nginx:
        container_name: nginx
        image: nginx:1.19.5-alpine
        restart: always
        volumes:
            - ../nginx:/etc/nginx/templates
    frontend:
        container_name: frontend
        build:
            context: ../../services/frontend
            args:
                NODE_IMAGE: node:15.3.0-alpine
        restart: always
