services:
    nginx:
        image: nginx:1.25.5-alpine
        restart: always
        ports:
            - ${WEBSITE_PORT}:6600
        volumes:
            - ../nginx:/etc/nginx/templates
    api:
        build:
            context: ../..
            dockerfile: configs/docker/Dockerfile
            target: api
            args:
                NODE_IMAGE: node:20.12.2-alpine
        restart: always
        environment:
            MESSAGE: ${MESSAGE}
