services:
    nginx:
        image: nginx:1.19.7-alpine
        restart: always
        volumes:
            - ../nginx:/etc/nginx/templates
    frontend:
        build:
            context: ../../services/frontend
            args:
                NODE_IMAGE: node:15.11.0-alpine
        restart: always
        entrypoint: pnpm start
