services:
    nginx:
        image: nginx:1.21.6-alpine
        restart: always
        ports:
            - ${WEB_PORT}:6600
        volumes:
            - ../nginx:/etc/nginx/templates
    api:
        build:
            context: ../../services/api
            args:
                NODE_IMAGE: node:18.1.0-alpine
        restart: always
        environment:
            MESSAGE: ${MESSAGE}
