services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            API_HOST: host.docker.internal
