version: "3.3"

services:
    nginx:
        container_name: nginx
        image: ${NGINX_IMAGE}
        restart: always
        ports:
            - ${WEB_PORT}:6600
        environment:
            FRONTEND_HOST: frontend
        volumes:
            - ../nginx:/etc/nginx/templates
        depends_on:
            - frontend
    frontend:
        container_name: frontend
        build:
            context: ../../services/frontend
            args:
                NODE_IMAGE: ${NODE_IMAGE}
        restart: always
        environment:
            PROJECT_NAME: ${PROJECT_NAME}
        entrypoint: yarn start
