services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        environment:
            API_HOST: api
        depends_on:
            - api
    api:
        extends:
            file: ./base.yml
            service: api
