services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        ports:
            - ${WEB_PORT}:6600
        environment:
            FRONTEND_HOST: frontend
        depends_on:
            - frontend
    frontend:
        extends:
            file: ./base.yml
            service: frontend
        entrypoint: pnpm start
