#!/bin/sh

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/..
DOCKER_CONFIGS_DIR=$ROOT_DIR/configs/docker

MODE=$1

shift

"$SCRIPTS_DIR"/clone-env
. "$ROOT_DIR"/.env
docker-compose -f "$DOCKER_CONFIGS_DIR"/docker-compose."$MODE".yml -p "$PROJECT_NAME"_"$MODE" "$@"
"$SCRIPTS_DIR"/prune

exit 0
